# SonarQube Project Configuration
sonar.projectKey=fitness-Tracker
sonar.projectName=Fitness Tracker
sonar.projectVersion=1.0.0

# Path to source directories
sonar.sources=server,public

# Path to test directories (if applicable)
# sonar.tests=tests

# Exclude third-party library folders
sonar.exclusions=node_modules/**,server/node_modules/**,public/assets/**,docs/**,Fitness_Chart/**

# Encoding of the source code
sonar.sourceEncoding=UTF-8

# Type of language analyzed
sonar.language=js
sonar.javascript.environments=node,browser
sonar.javascript.file.suffixes=.js

# Level of logging
sonar.log.level=INFO
