apiVersion: v1
kind: Secret
metadata:
  name: fitness-secrets
  namespace: fitness-tracker
type: Opaque
data:
  # Base64 encoded value of 'super-secret-jwt-key'
  JWT_SECRET: YzNWMlpYSXRjMlZqY21WMC1hbjNkMmgxYkdWNWN3PT0=
