apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fitness-tracker.fullname" . }}-app
  labels:
    {{- include "fitness-tracker.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ include "fitness-tracker.fullname" . }}-app
  template:
    metadata:
      labels:
        app: {{ include "fitness-tracker.fullname" . }}-app
      annotations:
        ad.datadoghq.com/{{ include "fitness-tracker.fullname" . }}-app.logs: >-
          [{"source":"nodejs","service":"{{ include "fitness-tracker.fullname" . }}-app"}]
    spec:
      containers:
        - name: fitness-tracker-app
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.app.port }}
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          env:
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: {{ include "fitness-tracker.fullname" . }}-configmap
                  key: MONGODB_URI
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "fitness-tracker.fullname" . }}-configmap
                  key: PORT
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "fitness-tracker.fullname" . }}-configmap
                  key: HOST
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ include "fitness-tracker.fullname" . }}-configmap
                  key: NODE_ENV
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "fitness-tracker.fullname" . }}-secrets
                  key: JWT_SECRET
            # Datadog APM tracking variables
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_TRACE_AGENT_PORT
              value: "8126"
            - name: DD_ENV
              value: "{{ .Values.global.environment }}"
            - name: DD_SERVICE
              value: "{{ include "fitness-tracker.fullname" . }}-app"
            - name: DD_VERSION
              value: "{{ .Chart.AppVersion }}"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fitness-tracker.fullname" . }}-service
  labels:
    {{- include "fitness-tracker.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "fitness-tracker.fullname" . }}-app
  ports:
  - port: {{ .Values.app.service.port }}
    targetPort: {{ .Values.app.port }}
  type: {{ .Values.app.service.type }}