apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "fitness-tracker.fullname" . }}-mongodb-pv
  labels:
    type: local
spec:
  storageClassName: {{ .Values.mongodb.storageClassName | quote }}
  capacity:
    storage: {{ .Values.mongodb.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.mongodb.pvHostPath | quote }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fitness-tracker.fullname" . }}-mongodb-pvc
spec:
  storageClassName: {{ .Values.mongodb.storageClassName | quote }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongodb.storage }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fitness-tracker.fullname" . }}-mongodb
  labels:
    {{- include "fitness-tracker.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "fitness-tracker.fullname" . }}-mongodb
  template:
    metadata:
      labels:
        app: {{ include "fitness-tracker.fullname" . }}-mongodb
    spec:
      containers:
      - name: mongodb
        image: {{ .Values.mongodb.image | quote }}
        ports:
        - containerPort: {{ .Values.mongodb.port }}
        volumeMounts:
        - name: mongodb-storage
          mountPath: /data/db
      volumes:
      - name: mongodb-storage
        persistentVolumeClaim:
          claimName: {{ include "fitness-tracker.fullname" . }}-mongodb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fitness-tracker.fullname" . }}-mongodb-service
  labels:
    {{- include "fitness-tracker.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "fitness-tracker.fullname" . }}-mongodb
  ports:
  - port: {{ .Values.mongodb.port }}
    targetPort: {{ .Values.mongodb.port }}
  type: ClusterIP