apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fitness-tracker.fullname" . }}-secrets
  labels:
    {{- include "fitness-tracker.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.app.jwtSecret }}
